### ISSUE TITLE
Umple compilation should behave the same way a Java compiler behaves

### ISSUE THREAD

**Issue by fred-lafleche** [umple/Umple-for-Vscode#16]
### **Description**
When pressing "Compile Umple Code", a piece of code that contains an error is highlighted, but no message is present in the console (a message is present when hovering on the highlighted text). We want to have a message in the console that is similar to the one we see in Umple Online and the Java compiler in VS code.

### **Current Behaviour**
Highlighted piece of problematic code:
![image](https://user-images.githubusercontent.com/31863167/119162545-7fc4e380-ba28-11eb-808f-fee99a5b2f79.png)

When hovering over:
![image](https://user-images.githubusercontent.com/31863167/119162585-8ce1d280-ba28-11eb-92c8-9e0fa4a7eeab.png)

### **Wanted Behaviour**
When running java code with java extension, an error is present in the console and when hovering over problematic code:
![image](https://user-images.githubusercontent.com/31863167/119162665-a551ed00-ba28-11eb-97e7-4189d5bb9530.png)

**Comment by Digized** [comment]
hey @fred-lafleche , i will try to take a look at this and resolve this soon. been relatively busy with work.

**Comment by Digized** [comment]
That's awesome to hear! If you have any questions, lmk, I haven't touched this in at least a year but I may remember some things, I did try to document all the non obvious things I thought of in the wiki. 

there maybe some things that are specifically tied to my vscode publishing account (digized), I was hoping to setup an action or something similar to continuously deploy but haven't had the chance to do that just yet. 

wrt assigning tickets, I believe we should have the same permissions and I am able to assign a ticket to you..

**Comment by fred-lafleche** [comment]
Hey @Digized , I am currently trying to make changes to the extension. I pulled the code, ran the debugger, a test vs code window appears, I create a .ump file but when pressing Generate or Compile, nothing happens. Are files even created when pressing generating or compiling in the testing environment?
Thanks for your help?

**Comment by Digized** [comment]
they should be, you can try running the tests, and that should work as expected. Make sure you have an umple compiler installed in the root directory (it should get installed by `npm install`).

**Comment by Digized** [comment]
#17 should allow you to fix your problem, we were trying to download from http, but now we use https
